[workspace]
members = [
    "contracts/src20-token",
    "contracts/token-vault",
    "predicates/multi-sig",
    "scripts/multi-asset-transfer",
]
[project]
authors = ["Nazeeh Vahora"]
entry = "main.sw"
license = "Apache-2.0"
name = "rosetta-stone-rs"

[dependencies]
